services:

# SonataAdminBundle configuration

    sar.admin.client:
        class: Siciarek\AdRotatorBundle\Admin\ClientAdmin
        tags: [{ name: sonata.admin, manager_type: orm, label: Clients }]
        arguments: [ null, Siciarek\AdRotatorBundle\Entity\Client, SonataAdminBundle:CRUD ]

    sar.admin.ad:
        class: Siciarek\AdRotatorBundle\Admin\AdAdmin
        tags: [{ name: sonata.admin, manager_type: orm, label: Sale }]
        arguments: [ null, Siciarek\AdRotatorBundle\Entity\Ad, SonataAdminBundle:CRUD ]

    sar.admin.ad_type:
        class: Siciarek\AdRotatorBundle\Admin\AdTypeAdmin
        tags: [{ name: sonata.admin, manager_type: orm, label: Ad types }]
        arguments: [ null, Siciarek\AdRotatorBundle\Entity\AdType, SonataAdminBundle:CRUD ]

    sar.admin.ad_price:
        class: Siciarek\AdRotatorBundle\Admin\AdPriceAdmin
        tags: [{ name: sonata.admin, manager_type: orm, label: Prices }]
        arguments: [ null, Siciarek\AdRotatorBundle\Entity\AdPrice, SonataAdminBundle:CRUD ]


sonata_admin:
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups:
                        - adrotator
        groups:
            adrotator:
                label: Ad Rotator
                items:
                    - sar.admin.ad
                    - sar.admin.client
                    - sar.admin.ad_type
                    - sar.admin.ad_price
