services:
    sar.request:
        class: Symfony\Component\HttpFoundation\Request

    sar.twig.extension:
        class: Siciarek\AdRotatorBundle\Twig\Extension\SiciarekAdRotatorExtension
        arguments: [ @service_container ]
        tags:
            -
                name:   twig.extension

    sar.request_listener:
        class: Siciarek\AdRotatorBundle\EventListener\RequestListener
        arguments: [ @service_container ]
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
