services:
    sar.request:
        class: Symfony\Component\HttpFoundation\Request
    sar.twig.extension:
        class: Siciarek\AdRotatorBundle\Twig\Extension\SiciarekAdRotatorExtension
        arguments: [ @service_container ]
        tags:
            -
                name:   twig.extension
