Siciarek\AdRotatorBundle\Entity\Ad:
    type: entity
    repositoryClass: AdRepository
    table: sar_ad_sale
    namedQueries:
        single: |
            SELECT a, t, c
                FROM __CLASS__ a
                LEFT JOIN a.client c
                LEFT JOIN a.type t
            WHERE
                a.enabled = true
            AND (a.starts_at <= CURRENT_TIMESTAMP() AND a.expires_at >= CURRENT_TIMESTAMP() OR a.everlasting = true)
            AND c.enabled = true
            AND a.id = :id
        available: |
            SELECT a, t, c
                FROM __CLASS__ a
                LEFT JOIN a.client c
                LEFT JOIN a.type t
            WHERE
                a.enabled = true
            AND (a.starts_at <= CURRENT_TIMESTAMP() AND a.expires_at >= CURRENT_TIMESTAMP() OR a.everlasting = true)
            AND c.enabled = true
            AND t.id = :type

    lifecycleCallbacks:
        prePersist: [ prePersist ]
        preUpdate: [ preUpdate ]

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title: ~
        price:
            type: decimal
            precision: 10
            scale: 2
            nullable: true
        displayed:
            type: integer
        clicked:
            type: integer
        slug:
            gedmo:
                slug:
                    fields:
                        - title
        path: ~
        leads_to:
            nullable: true
        enabled:
            type: boolean
        exclusive:
            type: boolean
        everlasting:
            type: boolean
        starts_at:
            type: datetime
            nullable: true
        expires_at:
            type: datetime
            nullable: true
        frequency:
            type: integer
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update

# RELATIONS -------------------------------------

    oneToMany:
        clicks:
            targetEntity: AdClick
            mappedBy: ad
    manyToOne:
        option:
            targetEntity: AdPrice
        type:
            targetEntity: AdType
            inversedBy: ads
        client:
            targetEntity: Client
            inversedBy: ads

