Siciarek\AdRotatorBundle\Entity\AdvertisementType:
    type: entity
    repositoryClass: AdvertisementTypeRepository
    table: sar_advertisement_type
    namedQueries:
        count: SELECT COUNT(o) FROM __CLASS__ o
        maxid: SELECT MAX(o.id) FROM __CLASS__ o
    id:
        id:
            type: integer
            generator:
                strategy: NONE
    fields:
        name: ~
        definition:
            type: json

    manyToMany:
        prices:
            targetEntity: AdvertisementPrice
            mappedBy: type
            cascade:
                - persist
            orderBy:
                price: ASC
    oneToMany:
        advertisements:
            targetEntity: Advertisement
            mappedBy: type
