Siciarek\AdRotatorBundle\Entity\AdvertisementPrice:
    type: entity
    repositoryClass: AdvertisementPriceRepository
    table: sar_ad_price
    namedQueries:
        ordered: SELECT o FROM __CLASS__ o ORDER BY o.price DESC
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        mainpage:
            type: boolean
        subpages:
            type: boolean
        duration:
            type: integer
            unsigned: true
        period: ~
        price:
            type: decimal
            precision: 10
            scale: 2

# RELATIONS -------------------------------------

    manyToMany:
        type:
            targetEntity: AdvertisementType
            inversedBy: prices
            joinTable:
                name: sar_ad_price_ad_type
                joinColumns:
                    price_id:
                        referencedColumnName: id
                        nullable: false
                        unique: false
                        onDelete: CASCADE
                inverseJoinColumns:
                    type_id:
                        referencedColumnName: id
                        nullable: false
                        unique: false
                        onDelete: CASCADE